### ISSUE TITLE
Sections with lot of entries are s...l...o...w...

### ISSUE THREAD

**Issue by Boyeen** [rob-nash/RRNCollapsableSectionTableView#3]
Nice work Rob, very useful. In my case I have multiple sections with large arrays of words (2k, up to 25k words in some cases). Expanding a section that big is instantaneous but collapsing, or switching to another section in singleOpenSelectionOnly mode) takes 30s or more... I've tried everything I can think of but can't find the inefficiency.  Suggestions?

**Comment by rob-nash** [comment]
Hi Boyeen. Wow that's a lot of rows! I create NSIndexPath's for all rows to be inserted or deleted, on the main thread. That will be why.

Will see if I can improve this now.

**Comment by rob-nash** [comment]
Just run profile and it looks like the generation of index paths is not the issue.

**Comment by rob-nash** [comment]
Looks like Apple's code bottlenecks here _setupAnimationsForDeletedCells.
All I can really suggest is avoid having more than 1000 rows per section.

I just tried to scroll 25000 rows with my thumb and my hand started to ache. Are you sure anyone is going to want a feature that physically hurts your hand ?

**Comment by Boyeen** [comment]
Hi Rob, All your points are fair. My app is a Scrabble word search (personal, not for the appstore where there are plenty already). 25k was an extreme case I agree but I can easily see 1500 4 letter words for example and even that list takes 30 seconds to collapse.... I use personal projects like this to learn and expand my skills and I have seen other apps with enormous lists work fine so there may be a trick... I will update you if I find anything. Thanks anyway. And thanks for sharing your work.

**Comment by rob-nash** [comment]
The reason I'm using ...AnimationTop and ...AnimationBottom is because Apple seems to have broken UITableViewRowAnimationAutomatic, which in the WWDC for iOS 5 'new features', suggests will do the appropriate animation for you.

Now I'm discovering that passing UITableViewRowAnimationNone and removing tableView begin / end updates, make no difference. The table view still animates!

Lots of reports online of the same thing. Looks like an issue in UIKit.

If it was working, I would try only animating the visible cells. But usually, Apple avoids rending stuff that is offscreen, so this is all a bit bizarre.

**Comment by rob-nash** [comment]
Xcode project on dropbox for you to see the issue in focus. I am sending this code to Apple and filing it as a radar. https://www.dropbox.com/s/upn9ee5svp11a1t/asdf.zip?dl=0

**Comment by Oleygen** [comment]
I've faced with same issue on my own project. Actually I did found your github googling "_setupAnimationsForDeletedCells" query. Looks like this can be solved if we will use reloadSections: instead of deleteCells:

**Comment by Oleygen** [comment]
test
